[tool.poetry]
name = "tfimm"
version = "0.0.1"
description = "Image models with pretrained weights in TensorFlow"
authors = ["Martins Bruveris"]

[tool.poetry.dependencies]
python = "~3.8"
numpy = "*"
tensorflow = ">2.5"

pyyaml = { version = "*", optional = true }
timm = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
flake8 = "*"
isort = "*"
pytest = "*"

[tool.poetry.extras]
timm = ["pyyaml", "timm"]

[tool.black]
line-length = 88
include = "\\.pyi?$"
exclude = """
/(
    \\.git
  | \\.tox
  | \\.venv
  | tmp
)/
"""

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
